live_config_reload = true

[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"
shape = "Beam"

[scrolling]
history = 10000

[window]
# decorations = "none"
# startup_mode = "Fullscreen"
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[font.normal]
# family="LiterationMonoNerdFont"
family="JetBrainsMonoNerdFont"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt | Shift", chars = "\u001BF" },
  { key = "Left",  mods = "Alt | Shift", chars = "\u001BB" },
]

